### ISSUE TITLE
Conflict with Model Types.

### ISSUE THREAD

**Issue by smatthews0** [grokability/kandji2snipe#23]
I've noticed an issue where Model Names can cause conflicts where the Model Identifier differ and was failing the script out. 

Model:MacBook Pro (16-inch, 2023)
Model Identifier:Mac14,10
M2 Pro

Model:MacBook Pro (16-inch, 2023)
Model Identifier:Mac14,6
M2 Max

I was getting the failure 
2024-09-23 16:51:44 - INFO - Processing entry 3 out of 151 - Device Name: *** - Device ID: ****
2024-09-23 16:51:44 - INFO - Could not find a model ID in Snipe-IT for: MacBook Pro (16-inch, 2023)
Traceback (most recent call last):
  File "***", line 790, in <module>
    create_snipe_model(newmodel)
  File "***", line 558, in create_snipe_model
    modelnumbers[jsonresponse['payload']['model_number']] = jsonresponse['payload']['id']
                                                            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
TypeError: 'NoneType' object is not subscriptable

Adding a new Model with the Model Identifier bypassed the error

**Comment by snipe** [comment]
Tat validation bug was fixed in Snipe-IT already

**Comment by smatthews0** [comment]
> That validation bug was fixed in Snipe-IT already. If you update to latest on master Snipe-IT, can you let me know if you're still seeing this issue?

Our Snipe Instance is on Snipe-IT version:v7.0.11 build 14904 (g6c0cf9447) but it's hosted for us So I'll need to take a look. It is fixed in 7.0.12?

**Comment by snipe** [comment]
> It is fixed in 7.0.12?

Yep - should be. Can you send an email to support@snipeitapp.com with your hosted subdomain so we can get you updated to latest?

**Comment by abranc94** [comment]
Hello, sorry to bring something back up from the past but I believe I am running into the same issue.

My org was testing Snipe out last year and we were running one of the versions in the 6.X range. We moved to Kandji in the last few weeks from JAMF so we were looking to get this going. After coming across this I've upgraded to  Version v8.0.4 - build 17704 (master) and am still experiencing the same issue as the above. Wondering if there's anything more I may need to adjust?

**Comment by kMikaZu** [comment]
I have a similar problem... 

Snipe IT version: v8.1.2 - build 17914 (master)

We've imported a fresh list of new Mac minis 2024 from a .csv (exported from Apple Business Manager). The Model Number was not inserted though. Reason: To be able to create labels and label the devices before rolling out. 

The Kandji2Snipe script creates a new Model during sync with the Model Number included `Mac16,10`

Existing Mac minis are untouched and the sync returns an error: 

```bash
2025-05-21 11:50:25 - INFO - Processing entry 4 out of 173 - Device Name: SN-Name - Device ID: <hidden>
2025-05-21 11:50:26 - INFO - No assets match <SN>
2025-05-21 11:50:26 - INFO - Creating a new asset in Snipe-IT for Kandji ID <Kandji ID-SN>
2025-05-21 11:50:26 - ERROR - Asset creation failed for asset <Kandji ID - SN> with error {'serial': ['The serial must be unique.']}
```

So the sync doesn't find the existing serial numbers and it tries to create new assets. The creation of those assets then of course fails, because the SN Asset Field must be unique. 

Even after deleting the created Model (created by the script) and entering the Model Number to the imported Model, the errors are the same. 

It looks definitely as if the script doesn't look up existing SN's and syncs them. It looks like a one-directional sync. There config has a `use_custom_pattern = no` value.

**Comment by snipe** [comment]
Can you try pulling latest from master of snipe-it? I think you may be running into an api issue we already fixed

**Comment by kMikaZu** [comment]
We will need to wait for PikaPods to release the update then. Is that the **8.1.3** you are referring to? 

Thanks!

**Comment by snipe** [comment]
I still don’t know pikapods are - I still think they’re a Pokémon I have not yet caught. 

But yes. 

I don’t know who or what Pikapods are, but more importantly, I don’t know how or when they provide those updates. They unfortunately don’t tell us anything. A new snipe-it release will be tagged in the next day or so, but I cannot speak to the lag time for pika.

**Comment by kMikaZu** [comment]
@snipe [The version on DockerHub](https://hub.docker.com/r/grokability/snipe-it/tags) is still version `8.1.2`, while the latest should be `8.1.16` . Why are these versions not in sync? 
In order for us to get the latest version on PikaPods, we need to have that latest version available on DockerHub as well. 

Thanks

**Comment by snipe** [comment]
You're looking in the wrong place. https://hub.docker.com/r/snipe/snipe-it/tags

**Comment by kMikaZu** [comment]
Hmm, I didn't find the latest versions but now I do. I've must have missed it. Thanks and sorry about that!

**Comment by kMikaZu** [comment]
You can ignore this. Got a message from PikaPods, they confirmed they were on the wrong release feed. So never mind! I was a little bit between wall and deck here, but it came out well!

**Comment by snipe** [comment]
It was a little confusing. We changed the namespace on Github for the repo, but then Dockerhub did some shenanigans which they wouldn’t help us undo. We didn’t want to move the Dockerhub version to that namespace since they were going to force us to lose all 10M+ pulls and all of our stars. (They don’t have a way to “move” a repo, apparently, so we’d lose allll of our stats if we switched namespaces there, so we ended up with the GH repo being on the new namespace, but the dockerhub version staying at the old address.)

I don’t think we can move the dockerhub part until they figure out a way for us to not lose years of stars and pull stats :( We reached out to them but they never answered.

**Comment by kMikaZu** [comment]
Thanks for the clarification! PikaPods told me they found the good version now, so everything should be fine. The new version doesn't fix the original problems stated in this Issue though. I deleted the manually added assets, did a sync and created new labels. For now, we are going to use Kandji as the main source to add new assets.
